Learning_django_1/Learning_django_1/urls.py
from django.contrib import admin
from django.urls import path,re_path
from basic_app import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$',views.index,name="index"),
    re_path(r'^basic_app/',include("basic_app.urls"))
]

Learning_django_1/basic_app/urls.py
from django.urls import path,re_path
from basic_app import views
from django.conf.urls import include

# TEMPLATE TAGGING

app_name = 'basic_app'

urlpatterns = [
    re_path(r'^relative/$',views.relative,name="relative"),
    re_path(r'^other/$',views.other,name="other"),
    re_path(r'^studentregs/$',views.studentRegs,name="studentregs"),
    path('deleteStudent/<int:roll>/',views.deleteStudent,name="deleteStudent")
]

Learning_django_1/basic_app/models.py
from django.db import models

# Create your models here.
class student(models.Model):
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    roll = models.CharField(max_length=50,unique=True)

    def __str__(self):
        return self.first_name + " " + self.last_name

Learning_django_1/basic_app/forms.py
from django import forms
from basic_app.models import student

class studentForm(forms.ModelForm):
    class Meta():
        model = student
        fields = "__all__"

Learning_django_1/basic_app/views.py
from django.shortcuts import render
from basic_app.models import student
from basic_app.forms import studentForm
# Create your views here.
def index(request):
    student_data = student.objects.all()
    return render(request,"basic_app/index.html",{'student':student_data})

def other(request):
    return render(request,"basic_app/other.html")

def relative(request):
    return render(request,"basic_app/relative_url_templates.html")

def studentRegs(request):
    form = studentForm()

    if request.method == "POST":
        form = studentForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            student_data = student.objects.all()
            return render(request,"basic_app/index.html",{'student':student_data})
        else:
            print("ERROR!!FORM INVALID")
    return render(request,"basic_app/add_student.html",{'form':form})

def deleteStudent(request,roll):
    student_data = student.objects.get(roll = roll)
    student_data.delete()
    new_student_data = student.objects.all()
    return render(request,"basic_app/index.html",{'student':new_student_data})

Learning_django_1/templates/basic_app/add_student.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
<form method="POST">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Submit" class="btn btn-primary">
</form>
{% endblock %}

Learning_django_1/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Django</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'admin:index' %}">Admin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'index' %}">Index</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" href="{% url 'basic_app:other' %}">Other</a>
        </li>
           <li class="nav-item">
          <a class="nav-link active" href="{% url 'basic_app:relative' %}">Relative</a>
        </li>
          </li>
           <li class="nav-item">
          <a class="nav-link active" href="{% url 'basic_app:studentregs' %}">Register</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

Learning_django_1/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
{% load my_extras %}
    <h1>Welcome to the Index Page</h1>
    <h1>We are learning template inheritance.</h1>
    {% if student %}
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Roll Number</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Delete Record</th>
        </tr>
        </thead>
        {% for data in student %}
        <tbody>
        <tr>
            <td>{{ data.roll }}</td>
            <td>{{ data.first_name|myCustomCapitalization:0 }}</td>
            <td>{{ data.last_name|myCustomCapitalization:0 }}</td>
            <td><a href="{% url 'basic_app:deleteStudent' data.roll %}">Delete</a></button></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endif %}
{% endblock %}

Learning_django_1/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
    <h1>Welcome to the Other Page</h1>
{% endblock %}

Learning_django_1/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
    <h1>Welcome to the Relative Url Page</h1>
    <a href="{% url 'basic_app:other' %}">OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">ADMIN PAGE</a>
    <a href="{% url 'index' %}">INDEX PAGE</a>
{% endblock %}